# Generated by Django 3.0.5 on 2020-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('userType', models.TextField(default='Student')),
                ('userStatus', models.TextField(default='ACTIVE')),
            ],
        ),
    ]
